reporter: "xcode"

disabled_rules:
  - force_cast
  - force_try
  - multiple_closures_with_trailing_closure

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id

line_length: 140


excluded:
  - Pods
